name: Build and Release Bing Wallpaper

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run tests
        run: go test -v ./...

      - name: Build Linux binary
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/bing-wallpaper

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/bing-wallpaper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

